//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.06.25 at 03:59:45 PM CEST
//


package com.bapits.labs.sample.aws.terraform.model.source.sampledata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="schemeID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemeAgencyID" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="schemeVersionID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"value"})
@XmlRootElement(name = "ID")
public class ID {

  @XmlValue
  protected String value;
  @XmlAttribute(name = "schemeID")
  protected String schemeID;
  @XmlAttribute(name = "schemeName")
  protected String schemeName;
  @XmlAttribute(name = "schemeAgencyID")
  @XmlSchemaType(name = "unsignedByte")
  protected Short schemeAgencyID;
  @XmlAttribute(name = "schemeVersionID")
  protected String schemeVersionID;

  /**
   * Gets the value of the value property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the schemeID property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSchemeID() {
    return schemeID;
  }

  /**
   * Sets the value of the schemeID property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSchemeID(String value) {
    this.schemeID = value;
  }

  /**
   * Gets the value of the schemeName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSchemeName() {
    return schemeName;
  }

  /**
   * Sets the value of the schemeName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSchemeName(String value) {
    this.schemeName = value;
  }

  /**
   * Gets the value of the schemeAgencyID property.
   * 
   * @return possible object is {@link Short }
   * 
   */
  public Short getSchemeAgencyID() {
    return schemeAgencyID;
  }

  /**
   * Sets the value of the schemeAgencyID property.
   * 
   * @param value allowed object is {@link Short }
   * 
   */
  public void setSchemeAgencyID(Short value) {
    this.schemeAgencyID = value;
  }

  /**
   * Gets the value of the schemeVersionID property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSchemeVersionID() {
    return schemeVersionID;
  }

  /**
   * Sets the value of the schemeVersionID property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSchemeVersionID(String value) {
    this.schemeVersionID = value;
  }

}
